[package]
name = "ashencolors-aoc2022"
version = "0.0.1"
authors = ["AshenColors"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
